model_name: "unsloth/llama-3.1-8b-Instruct-bnb-4bit"
max_seq_length: 1024
load_in_4bit: true
lora_r: 8
lora_alpha: 8
lora_dropout: 0
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
dataset_name: "philschmid/instruction-format-cot-alpaca"
output_dir: "lora_model_llama3"
training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  warmup_steps: 2
  max_steps: 10
  learning_rate: 2.0e-4
  logging_steps: 1
